# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

schedules:
- cron: "0 3 * * 1-5" # cron syntax defining a schedule
  displayName: Running at 3 in the morning from Monday to Friday # friendly name given to a specific schedule
  branches:
    include: 
    - main # which branches the schedule applies to
  always: true
